// ── Supabase generated types ───────────────────────────────────────────────
// This file is generated by the Supabase CLI. Do not edit manually.
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/types/database.ts
//
// Until the schema is finalised and connected, this file provides a minimal
// placeholder to keep TypeScript happy.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id:          string
          email:       string
          full_name:   string | null
          role:        string
          created_at:  string
          updated_at:  string
        }
        Insert: {
          id:          string
          email:       string
          full_name?:  string | null
          role?:       string
        }
        Update: {
          full_name?:  string | null
          role?:       string
          updated_at?: string
        }
      }
      event_config: {
        Row: {
          id:          number
          phase:       'pre_event' | 'event_day' | 'post_event'
          updated_at:  string
          updated_by:  string | null
        }
        Insert: {
          phase: 'pre_event' | 'event_day' | 'post_event'
        }
        Update: {
          phase?:      'pre_event' | 'event_day' | 'post_event'
          updated_at?: string
          updated_by?: string | null
        }
      }
      registrations: {
        Row: {
          id:            string
          user_id:       string
          activity_slug: string
          status:        string
          payment_status:string
          bib_number:    string | null
          created_at:    string
          updated_at:    string
        }
        Insert: {
          user_id:       string
          activity_slug: string
          status?:       string
          payment_status?:string
        }
        Update: {
          status?:        string
          payment_status?:string
          bib_number?:    string | null
          updated_at?:    string
        }
      }
      products: {
        Row: {
          id:           string
          name:         string
          slug:         string
          description:  string | null
          price_participant: number
          price_public: number
          image_url:    string | null
          category:     string | null
          sizes:        string[]
          stock:        number
          created_at:   string
        }
        Insert: {
          name:         string
          slug:         string
          price_participant: number
          price_public: number
          sizes?:       string[]
          stock?:       number
        }
        Update: {
          name?:        string
          price_participant?:number
          price_public?:number
          image_url?:   string | null
          stock?:       number
        }
      }
      orders: {
        Row: {
          id:         string
          user_id:    string
          status:     string
          total_tsh:  number
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id:   string
          status?:   string
          total_tsh: number
        }
        Update: {
          status?:     string
          updated_at?: string
        }
      }
    }
    Views:   Record<string, never>
    Functions: Record<string, never>
    Enums: {
      event_phase:         'pre_event' | 'event_day' | 'post_event'
      user_role:           'participant' | 'volunteer' | 'sponsor' | 'partner' | 'hq_admin'
      registration_status: 'pending' | 'confirmed' | 'paid' | 'cancelled' | 'checked_in'
      payment_status:      'pending' | 'completed' | 'failed' | 'refunded'
      order_status:        'pending' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled'
    }
  }
}
